version: '3.5'
services:

  ros_canopen_dev:
    container_name: ros_canopen_dev
    build: .
    tty: true
    privileged: true
    network_mode: host
    command: /bin/sh -c "while sleep 1000; do :; done"

  canopen-web-ui:
    container_name: canopen-web-ui
    build:
     context: ./canopen-web-ui
     dockerfile: Dockerfile
    ports:
     - "3000:3000"